
package Tela;

import classe.DadosCadastro;
import classe.ListaDados;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;



public class TelaInicial extends javax.swing.JFrame {
        
    ListaDados lista_dados = new ListaDados();
    DadosCadastro cadastro = new DadosCadastro();
        

    public TelaInicial() {
        
        initComponents();
        
        AtualizarTabela();
                   
    }
    
        public void geraAcessbilidade(){
            botao_salvar.setMnemonic(KeyEvent.VK_S);
        }

    
    public void AtualizarTabela(){
        
        
        String[] colunas = { "Data", "Hora", "Pressão Sistólica", "Pressão Diastólica", "Situação de estresse"};
        
        DefaultTableModel tableModel = new DefaultTableModel(colunas, 0);
        
        List<DadosCadastro> listaCompleta = ListaDados.getLista_dados();
                
        //Convertendo
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm");
        Date hora = Calendar.getInstance().getTime();
        String dataFormatada = sdf.format(hora);
    
        for (DadosCadastro c : listaCompleta) {
            String[] linha = {
                sdf.format(c.getData()),
                dtf.format(c.getHora()),
                String.valueOf(c.getPressao1()),
                String.valueOf(c.getPressao2()),
                c.getSituacao_estresse()
            };
            tableModel.addRow(linha);
        }      
            
            
        tabela_dados.setModel(tableModel);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        situacao_estresse = new javax.swing.JCheckBox();
        botao_salvar = new javax.swing.JButton();
        data_text = new javax.swing.JTextField();
        hora_text = new javax.swing.JTextField();
        pressao1_text = new javax.swing.JTextField();
        pressao2_text = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_dados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), new java.awt.Color(0, 51, 102))); // NOI18N
        jLayeredPane1.setToolTipText("Dados para cadastro");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setLabelFor(data_text);
        jLabel1.setText("Data:");
        jLabel1.setToolTipText("Informe a data que você tomou a medicação ");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setLabelFor(hora_text);
        jLabel2.setText("Hora:");
        jLabel2.setToolTipText("Informe a hora que você tomou a medicação ");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setLabelFor(pressao1_text);
        jLabel3.setText("Pressão Sistólica:");
        jLabel3.setToolTipText("Informe como estava a pressão sistólica no momento que você tomou a medicação ");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setLabelFor(pressao2_text);
        jLabel4.setText("Pressão diastólica:");
        jLabel4.setToolTipText("Informe como estava a pressão diastólica no momento que você tomou a medicação ");

        situacao_estresse.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        situacao_estresse.setText("Situação de estresse");
        situacao_estresse.setToolTipText("Informe se no momento da medicação, passou por alguma situação de estresse");
        situacao_estresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                situacao_estresseActionPerformed(evt);
            }
        });

        botao_salvar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botao_salvar.setText("Salvar");
        botao_salvar.setToolTipText("Salve as informações");
        botao_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_salvarActionPerformed(evt);
            }
        });

        data_text.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        hora_text.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        pressao1_text.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        pressao2_text.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(situacao_estresse, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(botao_salvar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(data_text, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(hora_text, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(pressao1_text, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(pressao2_text, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pressao2_text))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(data_text, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hora_text, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pressao1_text)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(situacao_estresse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botao_salvar)
                        .addGap(77, 77, 77))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(data_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hora_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(pressao1_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(pressao2_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(situacao_estresse)
                    .addComponent(botao_salvar))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(null);

        tabela_dados.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabela_dados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela_dados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_salvarActionPerformed
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
      

        DadosCadastro cadastro = new DadosCadastro();

        DateTimeFormatter formatterHora = DateTimeFormatter.ofPattern("HH:mm");
        
        /*VALIDAÇÕES------------------*/
        
        if (pressao1_text.getText().contains(",") && pressao1_text.getText().contains(".") && pressao2_text.getText().contains(",") && pressao2_text.getText().contains(".") && hora_text.getText().contains(".") && data_text.getText().contains(".")){
            JOptionPane.showMessageDialog(null,"O valor deve ser escrito sem vírgula nem ponto");
            return;
       }
        
        if (data_text.getText().isEmpty() && hora_text.getText().isEmpty() && pressao1_text.getText().isEmpty() && pressao2_text.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            return;  
   
        } else {                  
            String txtdata = data_text.getText(); 
            boolean palavra = txtdata.matches("[0-9]{2}[/][0-9]{2}[/][0-9]{4}");
            String txthora = hora_text.getText(); 
            boolean palavra2 = txthora.matches("[0-9]{2}[:][0-9]{2}");
            
                //DATA ERRADA
                if(palavra==false && palavra2==true){
                        JOptionPane.showMessageDialog(null, "Data precisa ser no formato DD/MM/AAAA. Exemplo: 10/10/2010 "); 
                        return;
                    }
                    //HORA ERRADA
                    else if(palavra==true && palavra2==false){
                        JOptionPane.showMessageDialog(null, "Hora precisa se no formato  HH:MM. Exemplo: 10:30"); 
                        return;
                    }
                        
                }
        
        //-------------------------------
   
        String data_paciente = data_text.getText();
        try {        
            Date data = sdf.parse(data_text.getText());
            cadastro.setData(data);
               

            LocalTime hora = LocalTime.parse(hora_text.getText(), formatterHora);

            cadastro.setHora(hora);
            cadastro.setPressao1(Integer.parseInt(pressao1_text.getText()));
            cadastro.setPressao2((Integer.parseInt(pressao1_text.getText())));
            String falseTrue = "";
        if (situacao_estresse.isSelected()){
           falseTrue = "Sim"; 
           cadastro.setSituacao_estresse(falseTrue);

        } else {
            falseTrue = "Não";
            cadastro.setSituacao_estresse(falseTrue);
        }

        ListaDados.adicionar(cadastro);
        
        AtualizarTabela();
        
        } catch (ParseException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botao_salvarActionPerformed

    private void situacao_estresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_situacao_estresseActionPerformed
        
    }//GEN-LAST:event_situacao_estresseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_salvar;
    private javax.swing.JTextField data_text;
    private javax.swing.JTextField hora_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pressao1_text;
    private javax.swing.JTextField pressao2_text;
    private javax.swing.JCheckBox situacao_estresse;
    private javax.swing.JTable tabela_dados;
    // End of variables declaration//GEN-END:variables
}

